#!/usr/bin/env bash
# this file is for the FIZZBUZZ file including multiples
x=1
while [ $x -le 100 ]
do
	if [ $((x%15)) == 0 ] 
	then 
		echo "FizzBuzz"
	elif [ $((x%5)) == 0 ]
	then 
		echo "Fizz"
	elif [ $((x%3)) == 0 ] 
	then
		echo "Buzz"
	else 
		echo "$x"
	fi
	((x++))
done
		
